### PR TITLE
Fix mark rotation to front

### LINKED ISSUE #105: Send point to back on click
Request from Jack.  Sometimes in the Outlier Explorer plots there are subjects who overlap with values at a given timepoint, and you cannot see the individual subject data until you click on a line.

Example: Cohort 2, Measure = QS – Severity of Alopecia Tool – Total Score, Site = 06.

Upon first glance it looks like 3 subjects, but there are 4, and there are 3 subjects with values hovering around 100 for the first few weeks.  Is there a way to tease out the data that occupy the same space? For example, some sort of horizontal offset? 

The group discussed and agreed that an automatic offset should be an easy fix for this.

### LINKED ISSUE #111: Add participant dropdown to small multiples.
dropdown should highlight selected participant in main chart on change

# Test notes
* Participant dropdown should appear above small multiples after clicking a line or point in the main chart.
* On change the corresponding participant should be highlighted in the main chart and the small multiples should update to reflect that participant's data.

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #105 
Closes #111

### CODE REVIEW

File: src/onResize/addEventListeners/functions/highlight.js [hunk 1]
```diff
@@ -7,10 +7,12 @@ export default function highlight() {
                 a.key.indexOf(this.selected_id) === 0
                     ? 2
                     : b.key.indexOf(this.selected_id) === 0
-                      ? -2
-                      : a.key.indexOf(this.hovered_id) === 0
-                        ? 1
-                        : b.key.indexOf(this.hovered_id) === 0 ? -1 : 0
+                        ? -2
```
Comment (samussiah) [inline src/onResize/addEventListeners/functions/highlight.js]: Forgot to update lines.  Will fix in the morning.

File: src/onResize/addEventListeners/functions/smallMultiples.js [hunk 2]
```diff
@@ -34,4 +44,34 @@ export default function smallMultiples() {
...
+                .remove();
+            delete context.hovered_id;
+            context.selected_id = d3
+                .select(this)
+                .selectAll('option:checked')
+                .text();
+            clearSelected.call(context);
+            applySelected.call(context);
+            clearHighlight.call(context);
+            applySelected.call(context);
```
Comment (samussiah) [inline src/onResize/addEventListeners/functions/smallMultiples.js]: two applications can't hurt right?

**Comment by rchronowic** [comment]
The points rotate when clicked.

When loaded in Firefox, the associated participant drop down extends past the page.

**Comment by samussiah** [comment]
ready for @jwildfire

File: src/onResize/addEventListeners/addNormalRangeEventListener.js [hunk 3]
```diff
@@ -0,0 +1,13 @@
+import clearHovered from './functions/clearHovered';
```
Comment (jwildfire) [inline src/onResize/addEventListeners/addNormalRangeEventListener.js]: nice touch making this clickable.

File: src/onResize/addEventListeners/functions/clearHovered.js [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+        })
+        .select('path')
+        .attr(this.config.line_attributes);
+    this.points
+        .filter(function() {
+            return !d3.select(this).classed('selected');
+        })
+        .select('circle')
+        .attr(this.config.point_attributes)
+        .attr('r', this.config.marks.find(mark => mark.type === 'circle').radius);
```
Comment (jwildfire) [inline src/onResize/addEventListeners/functions/clearHovered.js]: ugh - hate that this is needed to update the radius. we should clean this up in v2.0

File: src/onResize/addEventListeners/functions/clearSelected.js [hunk 5]
```diff
@@ -1,4 +1,12 @@
 export default function clearSelected() {
-    this.svg.selectAll('.line').classed('selected', false);
-    this.svg.selectAll('.point').classed('selected', false);
+    this.marks.forEach(mark => {
```
Comment (jwildfire) [inline src/onResize/addEventListeners/functions/clearSelected.js]: nice code, this is.

File: src/onResize/addEventListeners/functions/reorderMarks.js [hunk 6]
```diff
@@ -0,0 +1,17 @@
+export default function reorderMarks() {
```
Comment (jwildfire) [inline src/onResize/addEventListeners/functions/reorderMarks.js]: nicely done

File: src/onResize/addEventListeners/functions/smallMultiples/defineSmallMultiples.js [hunk 7]
```diff
@@ -1,25 +1,47 @@
...
+        this.multiples.settings.height =
+            this.multiples.settings.multiples_sizing.height +
+            (this.multiples.settings.margin.bottom ? this.multiples.settings.margin.bottom : 0);
 
-    multiples_settings.margin = { bottom: multiples_settings.margin.bottom || 20 };
+    this.multiples.settings.margin = { bottom: this.multiples.settings.margin.bottom || 20 };
 
-    this.multiples = createChart(this.wrap.select('.multiples').node(), multiples_settings);
+    //Add participant dropdown.
+    this.multiples.settings.selected_id = this.selected_id;
```
Comment (jwildfire) [inline src/onResize/addEventListeners/functions/smallMultiples/defineSmallMultiples.js]: Nice addition! ⭐️for going above and beyond the spec.

File: src/onResize/attachMarks.js [hunk 8]
```diff
@@ -0,0 +1,6 @@
+export default function attachMarks() {
+    this.marks.forEach(mark => {
```
Comment (jwildfire) [inline src/onResize/attachMarks.js]: Not sure what this bit is doing really ...

Comment (jwildfire) [reply src/onResize/attachMarks.js]: Is it actually called anywhere else?

**Comment by samussiah** [comment]
This one's ready for feature-testing @rchronowic !  Sounds like you've already tested point rotation, so only thing here is to test the participant dropdown that appears above the small multiples.

File: src/onResize/attachMarks.js (hunk 8 above)
Comment (samussiah) [reply src/onResize/attachMarks.js]: yeah, this just makes accessing `chart.points` and `chart.lines` more accessible down the line, instead of having to `chart.marks.find(mark => mark.type == 'circle|line')` every time they need accessing
