### PR TITLE
Fix tick rotation

### LINKED ISSUE #86: time_cols[].rotate_tick_labels and time_cols[].vertical_space do not change with X-axis control.
time_cols[].order needs to be explicitly set in the default settings because it is dictating the order of the lines between points even when the x-axis is linear.

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #86

### CODE REVIEW

File: build/safetyOutlierExplorer.js [hunk 1]
```diff
@@ -1372,6 +1381,7 @@
     function rangePolygon() {
         var _this = this;
 
+        console.log(this.config.normal_col_low);
```
Comment (pburnsdata) [inline build/safetyOutlierExplorer.js]: maybe remove this?
