### PR TITLE
Unscheduled visits

### LINKED ISSUE #68: Handle unexpected visits systematically
Depending on how unscheduled visits are displayed on the x-axis, the chart can have some unintended behavior.

(See related issue for Results Over Time: https://github.com/RhoInc/safety-results-over-time/issues/43)

If visits are displayed purely chronologically, the challenge is that you end up creating a new event type that shows up in the middle of the data, but for only a small number of data points.  See example of visits 2.1 and 4.1 below:
image

Our primary medical monitor user has proposed that to fix this, we sort all Unscheduled visits to the far right end of the chart, where they are still visible, but they don't interfere with seeing the data flow through expected visits.  The problem here is that the chart sometimes connects these points in a non-linear way:
example2

Proposed solutions:
1. Retain visits in numerical order, but create a toggle that lets the user "Hide unscheduled visits"
2. Force the chart to connect the dots in the same order as the axis is drawn

# Test notes
Test out the new "Visits without data" and "Unscheduled visits" controls in CAT with the safetyData/ADBDS.csv data file (not safetyData-queries/ADBDS.csv).

Confirm that:

* Unscheduled Visits and Visits with no data are shown/hidden when the toggle changes.
* Change measure to "Alkaline Phosphatase (ALP)" and confirm that visits with no data are shown/hidden when the toggle changes.
* Test with the above with groups active (settings: {groups:["RACE"]})
* Unscheduled visits are shown on initial load with {"unscheduled_visits":true}
* Visits with no data are shown on initial load with {"visits_without_data": false}
* Only the visits are hidden/shown when explicitly specified using {unscheduled_visit_values:["Unscheduled 2.1","Screening"]}

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #68

### CODE REVIEW

File: src/onDraw/updateSubjectCount.js [hunk 1]
```diff
@@ -1,40 +0,0 @@
-/*------------------------------------------------------------------------------------------------\
```
Comment (jwildfire) [inline src/onDraw/updateSubjectCount.js]: This lives elsewhere now??

File: src/onDraw/updateYDomain.js [hunk 2]
```diff
@@ -1,22 +0,0 @@
-export function updateYDomain(chart) {
```
Comment (jwildfire) [inline src/onDraw/updateYDomain.js]: Moved in refactor?

File: src/onInit/addVariables.js [hunk 3]
```diff
@@ -1,11 +1,20 @@
 export default function addVariables() {
+    const ordinalTimeSettings = this.config.time_cols
+        .filter(time_col => time_col.type === 'ordinal')
+        .pop();
```
Comment (jwildfire) [inline src/onInit/addVariables.js]: `array.pop()` instead of `array[0]` is cute. Probably a bit easier to read.

File: src/onInit/cleanData.js [hunk 4]
```diff
@@ -15,6 +15,7 @@ export default function cleanData() {
                 nRemoved > 1 ? 's have' : ' has'
             } been removed.`
         );
+    this.initial_data = clean;
```
Comment (jwildfire) [inline src/onInit/cleanData.js]: How dare you use `chart.initial_data` instead of good ol' `chart.super_raw_data`? Kids these days.

File: src/onPreprocess/defineMeasureData.js [hunk 5]
```diff
@@ -19,9 +18,4 @@ export default function defineMeasureData() {
 
         return !filtered;
     });
-    this.nested_measure_data = nest()
```
Comment (jwildfire) [inline src/onPreprocess/defineMeasureData.js]: Guessing this wasn't be used?

File: src/onDraw/updateSubjectCount.js (hunk 1 above)
Comment (samussiah) [reply src/onDraw/updateSubjectCount.js]: Changed it to updateParticipantCount ¯\_(ツ)_/¯

File: src/onDraw/updateYDomain.js (hunk 2 above)
Comment (samussiah) [reply src/onDraw/updateYDomain.js]: Moved to `onPreprocess/setYdomain`.

File: src/onInit/addVariables.js (hunk 3 above)
Comment (samussiah) [reply src/onInit/addVariables.js]: Yeah, but [`array.find()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) is the best option, but the one time I tried it out babel didn't add a polyfill so it failed in IE.

File: src/onInit/cleanData.js (hunk 4 above)
Comment (samussiah) [reply src/onInit/cleanData.js]: I'm not a super freak.

File: src/onPreprocess/defineMeasureData.js (hunk 5 above)
Comment (samussiah) [reply src/onPreprocess/defineMeasureData.js]: Right, only needed that in safety-results-over-time for the box plots.
